version: "3"

services:
  tunnel:
    build: ./server
    container_name: tunnel
    networks:
      - home
    ports:
      - 9090:9090
  http-vpn:
    build: ./server
    container_name: http-vpn
    network_mode: service:tunnel
    depends_on:
      - tunnel
    environment:
      PORT: 9090
  http:
    build: ./server
    container_name: plain-http
    networks:
      - home
    environment:
      PORT: 8080
    ports:
      - 8080:8080
networks:
  home:
    driver: bridge
